# Preparation

In [106]:
import json
import pandas as pd
from collections import Counter
import requests
import re
from pathlib import Path

In [66]:
home = Path.home()

# Functions

In [42]:
TOKEN_RE = re.compile(r"\d+|[^\W\d_]+|[.,/:;()\[\]-]")

def skeleton(text):
    out = []
    prev = None

    for tok in TOKEN_RE.findall(text):
        if tok[0].isdigit():
            kind = "N"
        elif tok[0].isalpha():
            kind = "W"
        else:
            kind = tok

        # Collapse consecutive words
        if kind == "W" and prev == "W":
            continue

        out.append(kind)
        prev = kind

    return "".join(out)

In [57]:
def walk_keys(obj, prefix=""):
    if isinstance(obj, dict):
        for key, value in obj.items():
            path = f"{prefix}.{key}" if prefix else key
            yield path
            yield from walk_keys(value, path)

# Analysis

## Initial data

In [67]:
structure_counter = Counter()


objects = []

with open(f"{home}/code/data/shbd/shb.jsonld.lines", "r", encoding="utf-8") as f:
	objects = [json.loads(row) for row in f]

skeleton_notes = []

example = {}
	
print(len(objects))

for object in objects:
	entity = object["@graph"][1]
	if "hasNote" in entity:
		note = entity["hasNote"][0]["label"]
		pattern = skeleton(note)
		skeleton_notes.append(pattern)
		structure_counter.update([pattern])

		example.setdefault(pattern, note)

print(len(skeleton_notes))
print(*skeleton_notes[:3], sep="\n")

79114
79024
W,W,W-W:WN:(W).-W:W,WN-N,N,N,W.N-N.-W.W-W,WN-N
W,W.W,W.-W:W,WN-N,N,N:N,W.N-N
W,W,W:W.-W:W,WN-N,N:N,W.N-N

### Count properties

In [61]:
property_counts = Counter()
subject_counts = Counter()

for object in objects:
	entity = object["@graph"][1]
	property_counts.update(walk_keys(entity))
      
	subjects = entity.get("instanceOf", {}).get("subject", [])
    
	subject_counts.update(
          subject["@id"]
              for subject in subjects
                    )

In [62]:
for key, count in property_counts.most_common():
    print(f"{count:>5}  {key}")

79114  @id
79114  @type
79114  category
79114  publication
79114  isPartOf
79114  part
79114  associatedMedia
79114  marc:primaryProvisionActivity
79114  marc:primaryProvisionActivity.year
79114  marc:primaryProvisionActivity.@type
79114  instanceOf
79114  instanceOf.@id
79024  hasNote

### Inspect structure of descriptions

In [53]:
print("| Count | Pattern | Example |")
print("|------:|---------|---------|")

for pattern, count in structure_counter.most_common(20):
    ex = example[pattern].replace("|", "\\|")  # Escape pipes if any
    print(f"| {count} | `{pattern}` | {ex} |")

| Count | Pattern | Example |
|------:|---------|---------|
| 842 | `W,W.,W.(WN,W.N-N.)` | Dalgren, L., Ur den nyaste tyska Arndtlitteraturen. (HT 1922, s. 247-249.) |
| 569 | `W,W.,W.(W.N(N),W.N-N.)` | Brulin, H., Das schwedische Archivwesen. (Archivalische Zeitschr. 38 (1929),s. 151-177.) |
| 566 | `W,W,W.(WN,W.N-N.)` | Lundberg, Erik, Nyare forskning över svensk byggnadshistoria. (Rig 1932,s. 105-127.) |
| 504 | `W,W,W.-WN.NN.` | Jagerskiold, Stig, Svea hovrätt jubilerar. - SvD 17.2 1964. |
| 417 | `W,W.,W.(WN(N),W.N-N.)` | Berghman, A., Heraldisk litteratur. (MRÄ 4 (1935), s. 9-38.) |
| 414 | `W,W,W.(W.N(N),W.N-N.)` | Floderus, Erik, Våra äldsta mynt. (Kooperatören. 17 (1930), s. 120-126.) |
| 321 | `W,W,W.(WN(N),W.N-N.)` | Söderberg, Bengt, Gotländska glasmålningar med länsherrevapen. (GA 5(1933), s. 37-44.) |
| 294 | `W,W,W.-WN(N),W.N-N.` | Åkerman, Sune, Projects and research priorities. - Historisk tidskrift 90 (1970),  s. 47-67. |
| 266 | `W,W,W.(WN/NN.)` | Leide, Arvid, Daniel Menlös och den Triewaldska samlingen. (SDS 23/2 1951.)  |
| 253 | `W,W,W.-WN(N),W.N-N.W.` | Malmborg, Boo von, Ett nyfunnet porträtt av Cecilia Vasa. - KT 32 (1963), s. 56-  57. Ill. |
| 245 | `W,W.,W.(WN:N/N.)` | Carlquist, G., De skånska herrgårdarnas arkiv och bibliotek. (SDS 1924:7/12.) |
| 191 | `W,W.,W.W.(WN,W.N-N.)` | Walde, O., Nicolaus Johannis Smalandius. Ett gammalt problem i svenskbibliotekshistoria. (NTBB 1926, s. 171-206.) |
| 181 | `W,W,W.-WN,W.N-N.W.` | Fogelström, Per Anders, Stockholmiana. - Biblis 1968, s. 61-100. Ill. |
| 170 | `W,W,W.W.(WN,W.N-N.)` | Söderberg, Tom, En släktbok och ett släktarkiv. De Åkerhielmska ätterna itryck och i handskrift. (HT 1928, s. 185-186.) |
| 161 | `W,W.,W.(W.WN,W.N-N.)` | Efvergren, C., Svenska bibliografier. (Om studier och hjälpmedel vid studier.Sthlm 1934, s. 149-173.) |
| 160 | `W,W,W.-W:WN(N),W.N-N.` | Du Rietz, Rolf, The concept of "bibliotype". - I: Text 1(1974), s. 78-92. |
| 159 | `W,W,W.-W:WN.NN` | Bergström, Harriet, Baltvågen för trettio år sedan dokumenteras i särskilt arkiv. - I: NSD 28.2 1974 |
| 151 | `W,W.W.,W.(WN,W.N-N.)` | Jacobowsky, G. V., Jämtlandslitteratur. (STÅ 1934, s. 267-272.) |
| 140 | `W,W,W.W:WN(N),W.N-N.` | Schnell, Ivar, Sörmland\ nyutkommen litteratur. — I: Sörmlandsbygden 43(1974), s. 145-152. |
| 140 | `W,W.,W.(W.W.N(N),W.N-N.)` | Nygren, E., Våra kyrkoarkiv. (Tidskr. för det svenska folkbildningsarbetet.10 (1922), s. 15-36.) |

## Enriched data

In [137]:
objects = []

with open(f"{home}/code/data/shbd/shb-cleaned-with-subjects.jsonld.lines", "r", encoding="utf-8") as f:
	objects = [json.loads(row) for row in f]
	
print(len(objects))

79060

In [138]:
property_counts = Counter()
subject_counts = Counter()

instances = []
for object in objects:
	entity = object["@graph"]["@graph"][1]
	property_counts.update(walk_keys(entity))
      
	subjects = entity.get("instanceOf", {}).get("subject", [])
	subject_counts.update(
          subject["@id"]
              for subject in subjects
                    )
	
	instances.append(entity)

print(instances[:3])

[{'@id': 'https://libris-qa.kb.se/dataset/shb/1#it', '@type': 'PhysicalResource', 'category': [{'@id': 'https://id.kb.se/term/saobf/ComponentPart'}, {'@id': 'https://id.kb.se/term/saobf/Print'}], 'instanceOf': {'@type': 'Monograph', 'category': [{'@id': 'https://id.kb.se/term/rda/Text'}]}, 'hasTitle': {'@type': 'Title', 'mainTitle': 'Malmö-litteratur', 'subtitle': 'bibliografiska noteringar för år1975 : (med tillägg från föregående år).'}, 'responsibilityStatement': 'Andersson, Per', 'partOf': [{'@type': 'Instance', 'label': 'Malmö, ISSN 0348-0909,44, 1976Även utg. i serien Malmö-litteratur, ISSN0348-0917', 'hasTitle': {'@type': 'Title', 'mainTitle': 'Malmö, ISSN 0348-0909,44, 1976'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0348-0909'}, 'extent': [{'@type': 'Extent', 'label': None}]}], 'hasNote': [{'@type': 'Note', 'label': 'Fullständig beskrivning (OCR) ur SHBD: Andersson, Per, Malmö-litteratur : bibliografiska noteringar för år1975 : (med tillägg från föregående år). - I: Malmö, ISSN 0348-0909,44, 1976, s. 98-124. - Även utg. i serien Malmö-litteratur, ISSN0348-0917'}, {'@type': 'Note', 'label': None}]}, {'@id': 'https://libris-qa.kb.se/dataset/shb/2#it', '@type': 'PhysicalResource', 'category': [{'@id': 'https://id.kb.se/term/saobf/ComponentPart'}, {'@id': 'https://id.kb.se/term/saobf/Print'}], 'instanceOf': {'@type': 'Monograph', 'category': [{'@id': 'https://id.kb.se/term/rda/Text'}]}, 'hasTitle': {'@type': 'Title', 'mainTitle': 'A bibliography of writings in English by or onrecent Swedish emigration historians'}, 'responsibilityStatement': 'Barton, H. Arnold', 'partOf': [{'@type': 'Instance', 'label': 'The Swedish pioneer, ISSN0039-7326, 27, 1976:3', 'hasTitle': {'@type': 'Title', 'mainTitle': 'The Swedish pioneer, ISSN0039-7326, 27, 1976:3'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0039-7326'}, 'extent': [{'@type': 'Extent', 'label': None}]}], 'hasNote': [{'@type': 'Note', 'label': 'Fullständig beskrivning (OCR) ur SHBD: Barton, H. Arnold, A bibliography of writings in English by or onrecent Swedish emigration historians. - I: The Swedish pioneer, ISSN0039-7326, 27, 1976:3, s. 215-221'}, {'@type': 'Note', 'label': None}]}, {'@id': 'https://libris-qa.kb.se/dataset/shb/3#it', '@type': 'PhysicalResource', 'category': [{'@id': 'https://id.kb.se/term/saobf/ComponentPart'}, {'@id': 'https://id.kb.se/term/saobf/Print'}], 'instanceOf': {'@type': 'Monograph', 'category': [{'@id': 'https://id.kb.se/term/rda/Text'}]}, 'hasTitle': {'@type': 'Title', 'mainTitle': 'Börringeklosters arkiv', 'subtitle': 'rapport.'}, 'responsibilityStatement': 'Carlsson, Ingemar', 'partOf': [{'@type': 'Instance', 'label': 'Ale, ISSN0345-0708, 1976:2', 'hasTitle': {'@type': 'Title', 'mainTitle': 'Ale, ISSN0345-0708, 1976:2'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0345-0708'}, 'extent': [{'@type': 'Extent', 'label': None}]}], 'hasNote': [{'@type': 'Note', 'label': 'Fullständig beskrivning (OCR) ur SHBD: Carlsson, Ingemar, Börringeklosters arkiv : rapport. - I: Ale, ISSN0345-0708, 1976:2, s. 44-45'}, {'@type': 'Note', 'label': None}]}]

In [151]:
extent = [{"@id": i["@id"], "extent": i["extent"][0]["label"]} for i in instances if "extent" in i and i["extent"][0]["label"][0].isalpha()]
extent_df = pd.json_normalize(extent)
extent_df.info()
extent_df.head(2)

pd.DataFrame(extent_df.value_counts(subset=["extent"])).head(50)

<class 'pandas.DataFrame'>
RangeIndex: 21421 entries, 0 to 21420
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   @id     21421 non-null  str
 1   extent  21421 non-null  str
dtypes: str(2)
memory usage: 334.8 KB

          count
extent
s. 4        178
s. 2         73
s. 1         32
s. 1-16      29
s. 1-8       26
s. 1-11      24
s. 1-12      22
s. 1-24      22
s. 1-7       22
s. 1-15      21
s. 3         20
s. 1-17      20
s. 1-9       19
s. 1-27      19
s. 1-13      19
s. 1-22      18
s. 1-30      18
s. 5-7       18
s. 1-14      17
s. 1-20      17
s. 5-12      16
s. 7-20      16
s. 14-15     16
s. 3-6       16
s. 1-10      16
s. 1-3       16
s. 25        16
s. 3-5       15
s. 3-7       15
s. 1-6       15
s. 1-18      15
s. 97        15
s. 38        14
s. 5-19      14
s. 1-5       14
s. 1-32      14
s. 1-4       14
s. 12-14     14
s. 12        14
s. 1-21      14
s. 1-34      14
s. 4-6       14
s. 11-15     14
s. 5-15      14
s. 5         14
s. 6-8       13
s. 6-9       13
s. 3-10      13
s. 81-83     13
s. 13-17     13

### Inspect seriesStatement

In [139]:
series_membership = [{"@id": i["@id"], "seriesMembership": i["seriesMembership"][0]} for i in instances if "seriesMembership" in i]

print(series_membership[:3])

[{'@id': 'https://libris-qa.kb.se/dataset/shb/10#it', 'seriesMembership': {'@type': 'Instance', 'label': 'Specialarbete / Bibliotekshögskolan, ISSN 0347-1128 ; 1976:158', 'hasTitle': {'@type': 'Title', 'mainTitle': 'Specialarbete / Bibliotekshögskolan, ISSN 0347-1128 ; 1976:158'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0347-1128'}}}, {'@id': 'https://libris-qa.kb.se/dataset/shb/28#it', 'seriesMembership': {'@type': 'Instance', 'label': 'Acta Bibliothecae regiae Stockholmiensis,ISSN 0065-1060 ; 28', 'hasTitle': {'@type': 'Title', 'mainTitle': 'Acta Bibliothecae regiae Stockholmiensis,ISSN 0065-1060 ; 28'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0065-1060'}}}, {'@id': 'https://libris-qa.kb.se/dataset/shb/52#it', 'seriesMembership': {'@type': 'Instance', 'label': 'Småskriftserien / Föreningen Gamla Vadstena, ISSN 0426-6587 ; 22', 'hasTitle': {'@type': 'Title', 'mainTitle': 'Småskriftserien / Föreningen Gamla Vadstena, ISSN 0426-6587 ; 22'}, 'identifiedBy': {'@type': 'ISSN', 'value': '0426-6587'}}}]

In [140]:
series_df = pd.json_normalize(series_membership)
series_df.info()
series_df.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 5491 entries, 0 to 5490
Data columns (total 9 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   @id                                       5491 non-null   str
 1   seriesMembership.@type                    5491 non-null   str
 2   seriesMembership.label                    5491 non-null   str
 3   seriesMembership.hasTitle.@type           5433 non-null   str
 4   seriesMembership.hasTitle.mainTitle       5433 non-null   str
 5   seriesMembership.identifiedBy.@type       33 non-null     str
 6   seriesMembership.identifiedBy.value       33 non-null     str
 7   seriesMembership.responsibilityStatement  84 non-null     str
 8   seriesMembership.extent                   736 non-null    object
dtypes: object(1), str(8)
memory usage: 386.2+ KB

,@id,seriesMembership.@type,seriesMembership.label,seriesMembership.hasTitle.@type,seriesMembership.hasTitle.mainTitle,seriesMembership.identifiedBy.@type,seriesMembership.identifiedBy.value,seriesMembership.responsibilityStatement,seriesMembership.extent
0,https://libris-qa.kb.se/dataset/shb/10#it,Instance,"Specialarbete / Bibliotekshögskolan, ISSN 0347...",Title,"Specialarbete / Bibliotekshögskolan, ISSN 0347...",ISSN,0347-1128,NaN,NaN
1,https://libris-qa.kb.se/dataset/shb/28#it,Instance,"Acta Bibliothecae regiae Stockholmiensis,ISSN ...",Title,"Acta Bibliothecae regiae Stockholmiensis,ISSN ...",ISSN,0065-1060,NaN,NaN

In [141]:
most_common_titles = pd.DataFrame(series_df.value_counts(subset=["seriesMembership.hasTitle.mainTitle"]))

most_common_titles.head(20)

                                          count
seriesMembership.hasTitle.mainTitle
GHT 6/4 1957                                  6
Särtr. ur Vasabladet                          6
Skolminnen                                    5
Festskr. utg. av Teol. fak. i Upps. 1941      5
Hembygdsböckerna                              4
UNT 1957: julnr                               4
1971                                          3
StT 1925: 10/5                                3
Memoarer och resor                            3
SDS 26/9 1954                                 3
Genos. 25 (1954)                              3
UNT 1956: julnr                               3
Växjöbl. 20/1 1960                            3
Särtr. ur Sv. läkartidn. 1948                 3
Studier i historisk metode ; 9                2
dowodcy                                       2
Värt att veta                                 2
SvD 1921: 17/7                                2
DN 1923: 30/9                                 2
SvD 1926: 10/1                                2

### Count properties and subjects

#### Properties

In [113]:
for key, count in property_counts.most_common():
    print(f"{count:>5}  {key}")

79060  @id
79060  @type
79060  category
79060  instanceOf
79060  instanceOf.@type
79060  instanceOf.category
78970  hasTitle
78970  hasTitle.@type
78970  hasTitle.mainTitle
78970  hasNote
78322  instanceOf.subject
67752  responsibilityStatement
41964  extent
23505  seriesMembership
 6222  partOf
 3141  hasTitle.subtitle

#### Subjects

In [110]:
for key, count in subject_counts.most_common():

    print(f"{count:>5}  {key}")

# Random stuff

In [ ]:
headers = {"Accept": "application/ld+json"}

query_string = f"instanceType:PhysicalResource title:({shbd_prepepd['mainTitle']}) title:({shbd_prepepd['subtitle']}) contributor:{shbd_prepepd['responsibility_statement']}* {shbd_prepepd['part_of_issn']} {shbd_prepepd['issn_from_note']}"


params = {"_q": "title:Hembergska+huset+i+Simrishamn contributor:Ehrnberg, G.*",
          #"_embellished": "false", Den här verkar inte göra något
          "_lens": "chips", # Den här behöver vara i plural
          "_stats": "false",
          "limit": 10}

res = requests.get("http://libris.kb.se/find?", params = params, headers=headers)
res.raise_for_status()
print(res.url)

print("Status:", res.status_code)
print("Number of results:", res.json()["totalItems"])
print("\nResult keys:", *res.json().keys(), sep=", ")

# Var finns den vanliga bibliografiska datan?
records = res.json()["items"]
print("\nItem keys:", *records[0].keys(), sep=", ")

print(records[0])

http://libris.kb.se/find?_q=title%3AHembergska%2Bhuset%2Bi%2BSimrishamn+contributor%3AEhrnberg%2C+G.%2A&_lens=chips&_stats=false&limit=10
Status: 200
Number of results: 1

Result keys:, @type, @id, search, itemOffset, itemsPerPage, totalItems, first, last, items, maxItems, @context

Item keys:, @type, meta, _categoryByCollection, @id, @reverse, hasTitle, language, contribution, reverseLinks
{'@type': 'Monograph', 'meta': {'mainEntity': {'@id': 'https://libris.kb.se/vc55wfk63mjdwll#work'}, '@type': 'VirtualRecord', '@id': 'https://libris.kb.se/vc55wfk63mjdwll#work-record'}, '_categoryByCollection': {'@none': [{'@type': 'ContentType', 'meta': {'mainEntity': {'@id': 'https://id.kb.se/term/rda/Text'}, '@type': 'Record', '@id': 'https://libris.kb.se/pnpsnkg0r5b6x092'}, '@id': 'https://id.kb.se/term/rda/Text', 'sameAs': [{'@id': 'https://id.kb.se/term/rda/content/text'}, {'@id': 'https://id.kb.se/term/rda/content/txt'}], 'prefLabelByLang': {'sv': 'Text', 'en': 'Text'}, 'code': 'txt', 'inScheme': {'@id': 'https://id.kb.se/term/rda'}}], '@type': None}, '@id': 'https://libris.kb.se/vc55wfk63mjdwll#work', '@reverse': {'instanceOf': [{'@type': 'PhysicalResource', '_categoryByCollection': {'@none': [{'@type': 'CarrierForm', 'meta': {'mainEntity': {'@id': 'https://id.kb.se/term/saobf/Print'}, '@type': 'Record', '@id': 'https://libris.kb.se/jq0mh5c5l2ff7sc2'}, '@id': 'https://id.kb.se/term/saobf/Print', 'prefLabelByLang': {'sv': 'Tryck', 'en': 'Print'}, 'inScheme': {'@id': 'https://id.kb.se/term/saobf'}}], '@type': None}, 'meta': {'mainEntity': {'@id': 'https://libris.kb.se/vc55wfk63mjdwll#it'}, '@type': 'Record', '@id': 'https://libris.kb.se/vc55wfk63mjdwll', 'sameAs': [{'@id': 'http://libris.kb.se/bib/10563636'}], 'controlNumber': '10563636', 'encodingLevel': 'marc:MinimalLevel'}, '@id': 'https://libris.kb.se/vc55wfk63mjdwll#it', '@reverse': {'itemOf': [{'@type': 'Item', '@id': 'https://libris.kb.se/kpwsd3kq4psxqzj#it', 'heldBy': {'@id': 'https://libris.kb.se/library/Ssm', 'isPartOf': {'@id': 'https://libris.kb.se/library/org/SSM'}}}, {'@type': 'Item', '@id': 'https://libris.kb.se/pt2jw9xv53tgcrb#it', 'heldBy': {'@id': 'https://libris.kb.se/library/Umdp', 'isPartOf': {'@id': 'https://libris.kb.se/library/org/UM'}}}]}, 'sameAs': [{'@id': 'http://libris.kb.se/resource/bib/10563636'}], 'hasTitle': [{'@type': 'Title', 'mainTitle': 'Hembergska huset i Simrishamn'}], 'publication': [{'@type': 'PrimaryPublication', 'country': {'@type': 'Country', 'meta': {'mainEntity': {'@id': 'https://id.kb.se/country/sw'}, '@type': 'Record', '@id': 'https://libris.kb.se/jf9xxz4ml0jrz74j'}, '@id': 'https://id.kb.se/country/sw', 'prefLabelByLang': {'sv': 'Sverige', 'en': 'Sweden'}, 'code': 'sw'}, 'place': [{'@type': 'Place', 'label': ['Lund']}], 'year': '1942'}]}]}, 'hasTitle': [{'@type': 'Title', 'mainTitle': 'Hembergska huset i Simrishamn'}], 'language': [{'@type': 'Language', 'meta': {'mainEntity': {'@id': 'https://id.kb.se/language/swe'}, '@type': 'Record', '@id': 'https://libris.kb.se/93lzl5lfc2l3hvc7'}, '@id': 'https://id.kb.se/language/swe', 'sameAs': [{'@id': 'https://id.kb.se/i18n/lang/sv'}], 'prefLabelByLang': {'sv': 'Svenska', 'en': 'Swedish'}, 'code': 'swe'}], 'contribution': [{'@type': 'PrimaryContribution', 'agent': {'@type': 'Person', 'familyName': 'Ehrnberg', 'givenName': 'Gösta'}}, {'@type': 'Contribution', 'agent': {'@type': 'Person', 'familyName': 'Åberg', 'givenName': 'Gustaf'}}], 'reverseLinks': {'totalItemsByRelation': {'itemOf': 2, 'itemOf.instanceOf': 2}, 'totalItems': 2, '@type': 'PartialCollectionView', '@id': 'https://libris.kb.se/find?o=https%3A%2F%2Flibris.kb.se%2Fvc55wfk63mjdwll%23work'}}

In [104]:
print(res.json()["stats"])

{'_predicates': [], 'sliceByDimension': {'librissearch:instanceType': {'dimension': 'librissearch:instanceType', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+instanceType:PhysicalResource'}, 'object': {'@id': 'PhysicalResource', '@type': 'Class', 'subClassOf': [{'@id': 'https://id.kb.se/vocab/Instance'}, {'@id': 'http://purl.org/dc/terms/PhysicalResource'}, {'@type': 'Restriction', 'onProperty': {'@id': 'https://id.kb.se/vocab/category'}, 'owl:onClass': {'hasValue': {'@id': 'https://id.kb.se/term/saobf/PhysicalForm'}, 'onProperty': {'@id': 'https://id.kb.se/vocab/broaderTransitive'}}, 'owl:minQualifiedCardinality': 1}], 'isDefinedBy': {'@id': 'https://id.kb.se/vocab/'}, 'labelByLang': {'en': 'Physical resource', 'sv': 'Fysisk resurs'}}}], 'maxItems': 100, '_connective': 'AND'}, 'librissearch:instanceCategory': {'dimension': 'librissearch:instanceCategory', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+instanceCategory:%22https://id.kb.se/term/saobf/Print%22'}, 'object': {'inScheme': {'@id': 'https://id.kb.se/term/saobf'}, 'prefLabelByLang': {'en': 'Print', 'sv': 'Tryck'}, '@type': 'CarrierForm', '@id': 'https://id.kb.se/term/saobf/Print'}}], 'maxItems': 100, '_connective': 'AND'}, 'language': {'dimension': 'language', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+language:%22lang:swe%22'}, 'object': {'prefLabelByLang': {'de': 'Schwedisch', 'en': 'Swedish', 'fr': 'suédois', 'sv': 'Svenska'}, 'sameAs': [{'@id': 'https://id.kb.se/i18n/lang/sv'}], '@id': 'https://id.kb.se/language/swe', 'code': 'swe', '@type': 'Language'}, '_selected': False}], 'maxItems': 100, '_connective': 'OR'}, 'librissearch:itemHeldByOrg': {'dimension': 'librissearch:itemHeldByOrg', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+library:%22libris:library/org/SSM%22'}, 'object': {'name': 'Statens maritima och transporthistoriska museer', 'code': 'SSM', '@type': 'bibdb:Organization', '@id': 'https://libris.kb.se/library/org/SSM'}, '_selected': False}, {'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+library:%22libris:library/org/UM%22'}, 'object': {'name': 'Umeå stadsbibliotek, lånecentralen', 'code': 'UM', '@type': 'bibdb:Organization', '@id': 'https://libris.kb.se/library/org/UM'}, '_selected': False}], 'maxItems': 1000, '_connective': 'OR'}, 'librissearch:yearPublished': {'search': {'template': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+%7B%3FyearPublished%7D', 'mapping': {'greaterThanOrEquals': '', 'variable': 'yearPublished', 'lessThanOrEquals': ''}}, 'dimension': 'librissearch:yearPublished', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+yearPublished:1942'}, 'object': '1942'}], 'maxItems': 10, '_connective': 'AND'}, 'librissearch:workType': {'dimension': 'librissearch:workType', 'observation': [{'totalItems': 1, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+workType:Monograph'}, 'object': {'@id': 'Monograph', '@type': 'Class', 'exactMatch': [{'@id': 'http://id.loc.gov/vocabulary/issuance/mono'}, {'@id': 'http://rdaregistry.info/termList/ModeIssue/1001'}], 'subClassOf': [{'@id': 'https://id.kb.se/vocab/Work'}], 'isDefinedBy': {'@id': 'https://id.kb.se/vocab/'}, 'labelByLang': {'en': 'Monograph', 'sv': 'Monografiskt verk'}, 'equivalentClass': [{'@id': 'http://id.loc.gov/ontologies/bibframe/Monograph'}]}}], 'maxItems': 100, '_connective': 'AND'}}, '_boolFilters': [{'totalItems': 0, 'object': {'prefLabelByLang': {'en': 'Exclude electronic legal deposit', 'sv': 'Exkludera elektroniska pliktleveranser'}, 'alias': 'excludeEplikt', 'raw': 'NOT (bibliography:"sigel:EPLK" AND itemHeldBy:"sigel:APIS" AND reverseLinks.totalItemsByRelation.itemOf.instanceOf=1)', '@type': 'Resource'}, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+excludeEplikt'}, '_selected': False}, {'totalItems': 0, 'object': {'prefLabelByLang': {'en': 'Exclude upcoming publications', 'sv': 'Exkludera kommande publiceringar'}, 'alias': 'excludePreliminary', 'raw': 'NOT recordType:VirtualRecord OR (NOT encodingLevel:("marc:PartialPreliminaryLevel" OR "marc:PrepublicationLevel"))', '@type': 'Resource'}, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+excludePreliminary'}, '_selected': False}, {'totalItems': 0, 'object': {'prefLabelByLang': {'en': 'Has cover/thumbnail', 'sv': 'Har omslags-/miniatyrbild'}, 'alias': 'existsImage', 'raw': 'image:*', '@type': 'Resource'}, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+existsImage'}, '_selected': False}, {'totalItems': 0, 'object': {'prefLabelByLang': {'en': 'Free online material', 'sv': 'Fritt online'}, 'alias': 'freeOnline', 'raw': 'instanceType:DigitalResource AND (usageAndAccessPolicy.label:gratis OR "associatedMedia.marc:publicNote":"fritt tillgänglig" OR usageAndAccessPolicy:("https://id.kb.se/policy/freely-available" OR "https://id.kb.se/policy/oa/gratis"))', '@type': 'Resource'}, 'view': {'@id': '/find?_q=title:Hembergska%2Bhuset%2Bi%2BSimrishamn+contributor:Ehrnberg%2C+G.*+freeOnline'}, '_selected': False}], '@id': '#stats'}

In [50]:
import re
rest = "Swedenborg : sökaren i naturens och andens värld :hans verk och efterföljd / Carl / Hej"
#rest = "Egerbladh, Ossian, Ur Lappmarkens bebyggelsehistoria. Umeå. 1-8. Se SHB 1961/70:7809.9 : Barsele : minnesskrift med anledning av byns tvåhundraåriga tillvaro.1970. 98 s.10 : Stensele 1741-1860 : de hundra äldsta nybyggesupptagningarna.1972. 237 s.11 : Fyra gamla Lyckselebyar : Björksele, Brattfors, Falträsk, Vägsele :denna utredning har utförts med anledning av Lycksele sockens 300-årsjubileum. 1973. 94 s. : ill."
subtitle = ""
title= ""
if ' : ' in rest:
	title, rest = rest.split(' : ', 1)
	print (title)
	print(rest)

	if ':' in rest:
		parts =  re.split(r" ([./])", rest, maxsplit=1)
		subtitle = parts[0]
		if len(parts) > 1:
			print(parts)
			rest = "".join(parts[1:])
print()
print(title)
print(subtitle)
print(rest)

Swedenborg
sökaren i naturens och andens värld :hans verk och efterföljd / Carl / Hej
['sökaren i naturens och andens värld :hans verk och efterföljd', '/', ' Carl / Hej']

Swedenborg
sökaren i naturens och andens värld :hans verk och efterföljd
/ Carl / Hej